import pexpect
import sys
print("#####################################")
print("Starting Configuring Interfaces on R4")
print("#####################################")
child1 = pexpect.spawn('ssh -oKexAlgorithms=+diffie-hellman-group1-sha1 -c aes128-cbc 192.168.56.152 -l iasonas')
child1.expect('Password:')
child1.sendline('ericsson')
child1.expect('R4>')
child1.sendline('enable')
child1.expect('Password:')
child1.sendline('ericsson')
child1.expect('R4#')
child1.sendline('terminal length 0')
child1.logfile=sys.stdout.buffer
child1.expect('R4#')
child1.sendline('conf t')
child1.expect('\(config\)#')
child1.sendline('interface fastEthernet2/0')
child1.expect('\(config-if\)#')
child1.sendline('ip address 192.168.12.1 255.255.255.0')
child1.expect('\(config-if\)#')
child1.sendline('no shutdown')
child1.expect('\(config-if\)#')
child1.sendline('exit')
child1.sendline('interface fastEthernet2/1')
child1.expect('\(config-if\)#')
child1.sendline('ip address 192.168.13.1 255.255.255.0')
child1.expect('\(config-if\)#')
child1.sendline('no shutdown')
child1.expect('\(config-if\)#')
child1.sendline('exit')
child1.close()
print("#####################################")
print("#End of Configuring Interfaces on R4#")
print("#####################################")

print("#####################################")
print("Starting Configuring Interfaces on R5")
print("#####################################")
child2 = pexpect.spawn('ssh -oKexAlgorithms=+diffie-hellman-group1-sha1 -c aes128-cbc 192.168.56.153 -l iasonas')
child2.expect('Password:')
child2.sendline('ericsson')
child2.expect('R5>')
child2.sendline('enable')
child2.expect('Password:')
child2.sendline('ericsson')
child2.expect('R5#')
child2.sendline('terminal length 0')
child2.logfile=sys.stdout.buffer
child2.expect('R5#')
child2.sendline('configure terminal')
child2.expect('\(config\)#')
child2.sendline('interface fastEthernet2/0')
child2.expect('\(config-if\)#')
child2.sendline('ip address 192.168.13.2 255.255.255.0')
child2.expect('\(config-if\)#')
child2.sendline('no shutdown')
child2.expect('\(config-if\)#')
child2.sendline('exit')
child2.sendline('interface fastEthernet2/1')
child2.expect('\(config-if\)#')
child2.sendline('ip address 192.168.23.3 255.255.255.0')
child2.expect('\(config-if\)#')
child2.sendline('no shutdown')
child2.expect('\(config-if\)#')
child2.sendline('exit')
child2.close()
print("#####################################")
print("#End of Configuring Interfaces on R5`#")
print("#####################################")
print("#####################################")
print("Starting Configuring Interfaces on R1")
print("#####################################")
child2 = pexpect.spawn('ssh -oKexAlgorithms=+diffie-hellman-group1-sha1 -c aes128-cbc 192.168.56.146 -l iasonas')
child2.expect('Password:')
child2.sendline('ericsson')
child2.expect('R1>')
child2.sendline('enable')
child2.expect('Password:')
child2.sendline('ericsson')
child2.expect('R1#')
child2.sendline('terminal length 0')
child2.logfile=sys.stdout.buffer
child2.expect('R1#')
child2.sendline('configure terminal')
child2.expect('\(config\)#')
child2.sendline('interface fastEthernet2/0')
child2.expect('\(config-if\)#')
child2.sendline('ip address 192.168.12.2 255.255.255.0')
child2.expect('\(config-if\)#')
child2.sendline('no shutdown')
child2.expect('\(config-if\)#')
child2.sendline('exit')
child2.sendline('interface fastEthernet2/1')
child2.expect('\(config-if\)#')
child2.sendline('ip address 192.168.23.2 255.255.255.0')
child2.expect('\(config-if\)#')
child2.sendline('no shutdown')
child2.expect('\(config-if\)#')
child2.sendline('exit')
child2.close()
print("#####################################")
print("#End of Configuring Interfaces on R1#")
print("#####################################")





